image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - mubaidr.vuejs-extension-pack
    - vscjava.vscode-java-pack

tasks:
  - init: mvn verify
  - command: mvn spring-boot:run

github:
  prebuilds:
    addBadge: true